sonar.organization=eduardohg017
sonar.projectKey=EduardoHG017_Laboratorio_No5_IngSTW
sonar.projectName=Laboratorio_No5_IngSTW
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml